// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
///
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         return macos;
//       case TargetPlatform.windows:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for windows - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }

//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyClg2aQneNNYjCTgLX8OlAvoLgYZQR53rE',
//     appId: '1:981273099181:web:264c12d163324c5c787f24',
//     messagingSenderId: '981273099181',
//     projectId: 'flutter-test-app-391115',
//     authDomain: 'flutter-test-app-391115.firebaseapp.com',
//     storageBucket: 'flutter-test-app-391115.appspot.com',
//     measurementId: 'G-H0D0BR1SN3',
//   );

//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyDP_yb5jKJNam4xvbW6QM_iY9OnzW4DL0k',
//     appId: '1:981273099181:android:b9c1416ba26d3bc2787f24',
//     messagingSenderId: '981273099181',
//     projectId: 'flutter-test-app-391115',
//     storageBucket: 'flutter-test-app-391115.appspot.com',
//   );

//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyDzuczHQ-gBv_yjaxccNPrtfJb3UDTHzxM',
//     appId: '1:981273099181:ios:20cf537e3b6a9066787f24',
//     messagingSenderId: '981273099181',
//     projectId: 'flutter-test-app-391115',
//     storageBucket: 'flutter-test-app-391115.appspot.com',
//     androidClientId: '981273099181-m503nejvbah23p1tmpcakl4qtdr93ggk.apps.googleusercontent.com',
//     iosClientId: '981273099181-gc9hst4fv7sqbchj5f171qj7o270a5q0.apps.googleusercontent.com',
//     iosBundleId: 'com.example.testApp',
//   );

  // static const FirebaseOptions macos = FirebaseOptions(
  //   apiKey: 'AIzaSyDzuczHQ-gBv_yjaxccNPrtfJb3UDTHzxM',
//     appId: '1:981273099181:ios:20cf537e3b6a9066787f24',
//     messagingSenderId: '981273099181',
//     projectId: 'flutter-test-app-391115',
//     storageBucket: 'flutter-test-app-391115.appspot.com',
//     androidClientId: '981273099181-m503nejvbah23p1tmpcakl4qtdr93ggk.apps.googleusercontent.com',
//     iosClientId: '981273099181-gc9hst4fv7sqbchj5f171qj7o270a5q0.apps.googleusercontent.com',
//     iosBundleId: 'com.example.testApp',
//   );
// }

